/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'techGadgets' : IDL.Null,
  'petGear' : IDL.Null,
  'fashion' : IDL.Null,
  'homeEssentials' : IDL.Null,
});
export const ProductBadge = IDL.Variant({
  'hot' : IDL.Null,
  'new' : IDL.Null,
  'viral' : IDL.Null,
  'sale' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Nat,
  'originalPrice' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'badge' : IDL.Opt(ProductBadge),
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'isTrending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'shippingAddress' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Time = IDL.Int;
export const FlashSale = IDL.Record({
  'endTime' : Time,
  'productIds' : IDL.Vec(IDL.Nat),
  'discountPercent' : IDL.Nat,
});
export const SortOption = IDL.Variant({
  'trending' : IDL.Null,
  'priceDesc' : IDL.Null,
  'rating' : IDL.Null,
  'priceAsc' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createFlashSale' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat, IDL.Nat], [], []),
  'createProduct' : IDL.Func([Product], [Product], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFlashSale' : IDL.Func([], [IDL.Opt(FlashSale)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func(
      [IDL.Opt(ProductCategory), IDL.Opt(SortOption)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateCartItemQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'techGadgets' : IDL.Null,
    'petGear' : IDL.Null,
    'fashion' : IDL.Null,
    'homeEssentials' : IDL.Null,
  });
  const ProductBadge = IDL.Variant({
    'hot' : IDL.Null,
    'new' : IDL.Null,
    'viral' : IDL.Null,
    'sale' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Nat,
    'originalPrice' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'badge' : IDL.Opt(ProductBadge),
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'shippingAddress' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Time = IDL.Int;
  const FlashSale = IDL.Record({
    'endTime' : Time,
    'productIds' : IDL.Vec(IDL.Nat),
    'discountPercent' : IDL.Nat,
  });
  const SortOption = IDL.Variant({
    'trending' : IDL.Null,
    'priceDesc' : IDL.Null,
    'rating' : IDL.Null,
    'priceAsc' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createFlashSale' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat, IDL.Nat], [], []),
    'createProduct' : IDL.Func([Product], [Product], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFlashSale' : IDL.Func([], [IDL.Opt(FlashSale)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(ProductCategory), IDL.Opt(SortOption)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateCartItemQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };