/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface FlashSale {
  'endTime' : Time,
  'productIds' : Array<bigint>,
  'discountPercent' : bigint,
}
export interface Product {
  'id' : bigint,
  'inStock' : bigint,
  'originalPrice' : [] | [bigint],
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : ProductCategory,
  'badge' : [] | [ProductBadge],
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'isTrending' : boolean,
}
export type ProductBadge = { 'hot' : null } |
  { 'new' : null } |
  { 'viral' : null } |
  { 'sale' : null };
export type ProductCategory = { 'techGadgets' : null } |
  { 'petGear' : null } |
  { 'fashion' : null } |
  { 'homeEssentials' : null };
export type SortOption = { 'trending' : null } |
  { 'priceDesc' : null } |
  { 'rating' : null } |
  { 'priceAsc' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'shippingAddress' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createFlashSale' : ActorMethod<[Array<bigint>, bigint, bigint], undefined>,
  'createProduct' : ActorMethod<[Product], Product>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getFlashSale' : ActorMethod<[], [] | [FlashSale]>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<
    [[] | [ProductCategory], [] | [SortOption]],
    Array<Product>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateCartItemQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];